#include "../macs.h"
#include <unistd.h>
DEF(int, unlink, (const char *pathname), ( pathname), (-1), EACCES,EBUSY,EFAULT,EIO,EISDIR,ELOOP,ENAMETOOLONG,ENOENT,ENOMEM,ENOTDIR,EPERM)
DEF(int, access, (const char *pn, int mo), ( pn, mo), (-1), EACCES,ELOOP,ENAMETOOLONG,ENOENT,ENOTDIR,EROFS,EFAULT,EIO,ENOMEM)
DEF(int, chdir, (const char *pn), ( pn), (-1), EACCES,EFAULT,EIO,ELOOP,ENAMETOOLONG,ENOENT,ENOMEM,ENOTDIR)
DEF(int, chown, (const char *pn, uid_t o, gid_t g), ( pn, o, g), (-1), EACCES,EFAULT,EIO,ELOOP,ENAMETOOLONG,ENOENT,ENOMEM,ENOTDIR,EPERM)
DEF(int, close, (int fd), ( fd), (-1), EINTR,EIO,ENOSPC,EDQUOT)
DEF(int, dup, (int fd), ( fd), (-1), EBADF,EMFILE)
DEF(int, dup2, (int fd1, int fd2), ( fd1, fd2), (-1), EBADF,EMFILE,EIO)
DEF(int, execv, (const char *file, char *const *argv), ( file, argv), (-1), EACCES,EAGAIN,EFAULT,EIO,EISDIR,ELIBBAD,ELOOP,EMFILE,ENOENT,ENOEXEC,EPERM)
DEF(int, execve, (const char *file, char *const *argv, char *const *envp), ( file, argv, envp), (-1), EACCES,EAGAIN,EFAULT,EIO,EISDIR,ELIBBAD,ELOOP,EMFILE,ENOENT,ENOEXEC,EPERM)
DEF(int, execvp, (const char *file, char *const *argv), ( file, argv), (-1), EACCES,EAGAIN,EFAULT,EIO,EISDIR,ELIBBAD,ELOOP,EMFILE,ENOENT,ENOEXEC,EPERM)
DEF(pid_t, fork, (), (), (-1), EAGAIN,ENOMEM)
DEF(char*, getcwd, (char *buf, size_t size), ( buf, size), (NULL), EACCES,ENOENT,ENOMEM)
DEF(int, gethostname, (char *name, size_t len), ( name, len), (-1), EPERM)
DEF(int, link, (const char *old, const char *new), ( old, new), (-1), EACCES,EDQUOT,EEXIST,EFAULT,EIO,ELOOP,EMLINK,ENAMETOOLONG,ENOENT,ENOMEM,ENOTDIR,EPERM,EROFS)
DEF(ssize_t, read, (int fd, void *m, size_t n), ( fd, m, n), (-1), EAGAIN,EFAULT,EINTR,EIO,EISDIR)
DEF(ssize_t, readlink, (const char *path, char *buf, size_t size), ( path, buf, size), (-1), EACCES,EINVAL,EIO,ELOOP,ENAMETOOLONG,ENOENT,ENOTDIR)
DEF(int, rmdir, (const char *pathname), ( pathname), (-1), EACCES,EBUSY,EFAULT,EINVAL,ELOOP,ENAMETOOLONG,ENOENT,ENOMEM,ENOTDIR,ENOTEMPTY,EPERM,EPERM,EROFS)
DEF(ssize_t, write, (int fd, const void *m, size_t n), ( fd, m, n), (-1), EAGAIN,EDQUOT,EFAULT,EINTR,EIO,ENOSPC)
